### ISSUE TITLE
xray-reporter.js . getdate() 5.5 as TimeZone resulting in incorrect import to xray

### ISSUE THREAD

**Issue by wolfy027** [lukas-reineke/protractor-xray-reporter#14]
Executed 18 of 18 specs SUCCESS in 2 mins 23 secs.
Request Url:
**https://sandbox.xpand-it.com/rest/raven/1.0/import/execution**

Request Body
```
{
  info: { description: undefined, version: '1.0', summary: 'Google Chrome' },
  tests: [
    {
      testKey: 'CALC-1965',
      start: '2019-11-13T13:20:52+05.5:00',
      steps: [Array],
      status: 'PASS',
      finish: '2019-11-13T13:23:15+05.5:00'
    }
  ]
}
```

```
(node:43599) UnhandledPromiseRejectionWarning: Error: Error: java.lang.IllegalArgumentException: Invalid format: "2019-11-13T13:20:52+05.5:00" is malformed at ".5:00"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:899)
        at com.xpandit.raven.c.R.a(Unknown Source)
        at com.xpandit.raven.service.executionresult.impl.ExecutionResultImportServiceImpl.a(Unknown Source)
```

**Comment by lukas-reineke** [comment]
Thanks for the bug report.
Indeed this is broken for timezones that don't have a full number offset.


PRs to fix this are welcome :pray:
